In [1]:
import numpy as np

## Standarization


$ x_{stadandarized} = \frac {x - \mu} {\sigma} $

## Normalizing min-max

$ x_{normalized} = \frac {x - min} { max - min } $

$ \mu ,  \sigma $ , are the the median and standard deviation 


#### min - max are the minimun and maximum value

#### x is the variable

In [2]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler

In [4]:
data = np.array([[1,2,3,4,5],[5,6,7,8,9],[10,11,12,13,14],[15,16,17,18,19],[20,21,22,23,24]])

In [5]:
scaler = StandardScaler()

In [6]:
scaled_data = scaler.fit_transform(data)

print("Scaled Data")
print(scaled_data)

Scaled Data
[[-1.35411306 -1.35411306 -1.35411306 -1.35411306 -1.35411306]
 [-0.76536825 -0.76536825 -0.76536825 -0.76536825 -0.76536825]
 [-0.02943724 -0.02943724 -0.02943724 -0.02943724 -0.02943724]
 [ 0.70649377  0.70649377  0.70649377  0.70649377  0.70649377]
 [ 1.44242478  1.44242478  1.44242478  1.44242478  1.44242478]]


In [7]:
min_max_scaler = MinMaxScaler()

normalized_data = min_max_scaler.fit_transform(data)
print("Datos Normalizados:")
print(normalized_data)

Datos Normalizados:
[[0.         0.         0.         0.         0.        ]
 [0.21052632 0.21052632 0.21052632 0.21052632 0.21052632]
 [0.47368421 0.47368421 0.47368421 0.47368421 0.47368421]
 [0.73684211 0.73684211 0.73684211 0.73684211 0.73684211]
 [1.         1.         1.         1.         1.        ]]
